### ISSUE TITLE
No GUI is displayed as mentioned in the paper

### ISSUE THREAD

**Issue by juzer10** [SoftwareEngineeringToolDemos/ICSE-2012-EXSYST#5]

**Comment by rkvardhi** [comment]
Paper says that "After invoking EXSYST with the program under test, it autonomously generates input sequences in an **invisible virtual GUI**, reporting any application failures as encountered." and authors of the paper transformed the generated tests into UISpec4J tests with a couple of regular expressions and search & replace for demonstration purposes.
